### PR TITLE
Minor fix to broken merge.

### PR DESCRIPTION
**Pull request by mathuin**
At some point when HEAD was rebased or merged with crouton/master, one
conflict went unresolved.  I resolved the conflict and was able to use
crouton to successfully generate an arch chroot.

### CODE REVIEW

**Comment by Watney** [comment]
@mathuin Nice work! If you should write down your steps for others to follow (i.e., a Guide), I'd be super interested. My skill level isn't up for the task of installing Arch with an up-to-date crouton. Thanks! (Maybe something for the Arch Wiki?)

**Comment by drinkcat** [comment]
@mathuin : Thanks, sorry for that ,-)

I'm happy to merge it but I'd need you to sign the [Individual Contributor License Agreement](https://cla.developers.google.com/clas/new?kind=KIND_INDIVIDUAL&domain=DOMAIN_GOOGLE) first, since this will get merged into the main crouton at some point. Thanks!

**Comment by mathuin** [comment]
@drinkcat I have indeed signed the ICLA, how do I prove that to you?

@Watney all I did was use this branch as I would use the master branch of crouton but with "-r arch -t xiwi,cli-extra" as the arguments.  Nothing special. :-)

**Comment by Watney** [comment]
@mathuin hmm, okay, I'll look closer. Thanks!

**Comment by drinkcat** [comment]
Merged. Thanks!

**Comment by mathuin** [comment]
I just learned about the test suite yesterday and ran this branch against the suite.  It failed on the xorg target for arch.  I am investigating this issue, and will create another branch to fix it.

**Pull request merged**
